add data preprocessing, data split, and evaluation files for four dat…
JzHuai0108/PointNetVlad-Pytorch pull request #1
Opened 2023-09-10 10:46 UTC by CYWCC

Add data preprocessing, training and testing partitioning, and testing files for four datasets.

2023-09-12 14:57 UTC, JzHuai0108 requested changes
主体没啥问题。感觉需要修改一下语法和参数传入。

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/test_slerp.py
> +def rot_slerp_batch(keytimes, keyquats, querytimes):
添加如下注释：This function requires that the querytimes are within the boundaries of the keytimes. Be careful calling this function.

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/test_slerp.py
> +def pos_interpolate_batch(keytimes, keypositions, querytimes):
This function will return the boundary values of keypositions if querytimes are out of the boundaries of keytimes.

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +def interpolation(gt_times, gt_positions, gt_quats, radar_times):
这个函数被定义了6.7次。能放到一个文件中，然后import么？

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +from test_slerp import *
不要用×。 这样有点乱。如果想简洁的话，import test_slerp as ts.

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +            if i == 0:
加个注释：为啥跳第一行？

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +    submap_pcd = o3d.geometry.PointCloud()
感觉不用这么重的o3d吧。直接np操作就够了。
a = a[indices, :]

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +        sigle_T_Bs = np.hstack((rotation_matrix, xyz))  # 将xyz和rotation矩阵按列拼接
singlechip_T_base

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +        sigle_T_Bs = np.hstack((rotation_matrix, xyz))  # 将xyz和rotation矩阵按列拼接
命名不要用缩写，除非本科以上的人都知道的缩写。

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +    data_path = '/path/to/radar_reloc_data/coloradar/'
用argparse提示用户传参数和设置参数。这么写比用你的本地路径更要求用户改。

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +    sub_size = 5
改个名字，frame_winsize

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +        sigle_T_Bs = np.hstack((rotation_matrix, xyz))  # 将xyz和rotation矩阵按列拼接
你这里应该是base_T_singlechip吧？ 你觉得base_T_singlechip有歧义么？

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +        seq_num = int(re.findall(r'\d+', seq)[-1])
seq_num = int(seq[-1]) 不香么？

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +            points = np.array(list(radar))
points = np.array(radar)可以吧？

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +                continue
加个注释：So the interpolation for poses will succeed.

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +        W_T_R = [pose.dot(Bs_T_sigle) for pose in interp_poses]
dot换成np.matmul(pose, base_T_singlechip)

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +            submap_name = str(count).zfill(6) + ".bin"
用以纳秒为单位的时间戳给submap命名，参考pointnetvlad dataset. for example, 1403775421889009.bin

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +            submap_poses.append(submap_pose)
pose 加上时间戳？

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_coloradar.py
> +                f.write(' '.join(str(x) for x in pose_with_yaw) + '\n')
保存一下对应的纳秒为单位的时间戳？

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_inhouse.py
> +def random_down_sample(pc, sample_points):
重复的函数放到一个文件中，然后import

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_inhouse.py
> +        calib = np.fromstring(lines[0], dtype=np.float32, sep=' ').reshape(3, 4)
calib 用np.float64吧。缺省应该就是np.float64。

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_inhouse.py
> +def comput_trans(I_T_R, c_pose, j_pose):
现在这个变换简化了，直接N和E是一个坐标系了。所以都用E吧。

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_inhouse.py
> +    N_R_R = center_pose[:3,:3] @ I_T_R[:3,:3]
可以都用E吧。

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_inhouse.py
> +    data_path = '/path/to/radar_reloc_data/radar_reloc_data/inhouse/'
argparse

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_inhouse.py
> +                points = np.array(list(radar))
np.array(radar)?

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_inhouse.py
> +            submaps_poses_path = os.path.join(save_path, save_folder, group_name, seq_name + '_poses.txt')
能把这一部分分解成几个小函数么？这样重用函数可以降低代码量。和我的阅读工作量。

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_mscrad4r.py
> +    M_R_Ic = c_pose[:3, :3]
现在这个也简化了，直接提供的GT就是E_T_I

2023-09-12 14:57 UTC, JzHuai0108 commented on evaluate_radar.py
> +print(device)
print('Evaluating with device {}'.format(device))

2023-09-12 14:57 UTC, JzHuai0108 commented on data_preparation/gen_submaps_mscrad4r.py
> +            target_submap = I_T_R.dot(target_submap.T).T[:, :3]
Good.

2023-09-12 14:57 UTC, JzHuai0108 commented on train_pointnetvlad.py
> +        train_writer.add_scalar("Val Recall", eval_recall[1], epoch)
why [1]?

2023-09-12 14:57 UTC, JzHuai0108 commented on train_pointnetvlad.py
> +# TEST_QUERIES = get_queries_dict(cfg.TEST_FILE)
why not use TEST_QUERIES?

2023-09-12 14:57 UTC, JzHuai0108 commented on train_pointnetvlad.py
> +cfg.TRAIN_FILE = 'generating_queries/radar_split/training_queries_long_radar.pickle'
能不能删除这一行？然后通过argparse传进来？

2023-09-12 14:57 UTC, JzHuai0108 commented on train_pointnetvlad.py
> +cfg.NUM_POINTS = 512
删除这一行。通过argparse传进来？

2023-09-12 14:57 UTC, JzHuai0108 commented on evaluate_radar.py
> +    resume_filename = cfg.LOG_DIR + cfg.MODEL_FILENAME
os.path.join(cfg.LOG_DIR, cfg.MODEL_FILENAME)

2023-09-12 14:57 UTC, JzHuai0108 commented on evaluate_radar.py
> +    parser = argparse.ArgumentParser()
Good.

2023-09-12 14:57 UTC, JzHuai0108 commented on evaluate_radar.py
> +            if g_key != q_key:
Why this? I think I found the reason a while ago, but I forgot it. 所以加个注释？

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_training_tuples_radar.py
> +base_path = '/media/cyw/CYW-ZX2/radar_reloc_data/'
argparse

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +    base_path = '/media/cyw/CYW-ZX2/radar_reloc_data/'
argparse

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
delete. 尽量不要用BASE_DIR，用参数传递吧。

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +            df_locations['data_id'] = df_locations['data_id'].apply(lambda x: str(x).zfill(6))
用纳秒时间戳做data_id吧。

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +                query.update(query)
这句有啥用？语法上没用啊。

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +        database = {}
为啥不放到for loop 里面？

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +                for index, row in df_test.iterrows():
前面加上query = {}.

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +                for index, row in df_locations.iterrows():
前面加上database = {}

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +            true_index = np.array(index)[np.where(yaw_diff > 75)[0]]
感觉有点绕，能简化一下这个yaw_diff的判断么？

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +            true_index = np.array(index)[np.where(yaw_diff > 75)[0]]
感觉可以用一下np.setdiff1d

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_training_tuples_radar.py
> +        yaw_diff = 120 - np.abs(yaw - df_centroids.iloc[positive_candis]["yaw"])
120能作为参数传入么？

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_training_tuples_radar.py
> +        positives = np.array(positive_candis)[np.where(yaw_diff > 75)[0]].tolist()
75作为参数？

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +            yaw_diff = 120 - np.abs(yaw - df_database.iloc[index]["yaw"])
120 和75作为参数传递？

2023-09-12 14:57 UTC, JzHuai0108 commented on generating_queries/generate_training_tuples_radar.py
> +save_path = "./radar_split/training_queries_short_radar.pickle"
参数传入一下主目录？

2023-09-13 07:59 UTC, CYWCC commented on data_preparation/gen_submaps_coloradar.py
> +            points = np.array(list(radar))
试了,不行

2023-09-15 12:51 UTC, JzHuai0108 approved these changes
My concerns are mostly addressed except a few requests for comments. For instance,
the structure of query_sets, database_sets. A comment about the range of yaw [-180, 180] would clarify the positive sample criteria.

2023-09-15 12:51 UTC, JzHuai0108 commented on evaluate_radar.py
> +    DATABASE_SETS = get_sets_dict(cfg.EVAL_DATABASE_FILE)
add a comment briefly describing database_sets structure?

2023-09-15 12:51 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +            query_sets[seq] = query
decrease indent by 4 spaces

2023-09-15 12:51 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +            yaw_diff = 120 - np.abs(yaw - df_database.iloc[index]["yaw"])
maybe abs(yaw1 - yaw2) < 75 deg or abs(yaw1 -yaw2) > 180 and abs(abs(yaw1 - yaw2) - 360) < 75

2023-09-15 12:51 UTC, JzHuai0108 commented on train_pointnetvlad.py
> +# import evaluate
if cfg.train_for_lidar:
    import evaluate
else:
    import evaluate_radar

2023-09-15 12:51 UTC, JzHuai0108 commented on generating_queries/generate_test_sets_radar.py
> +            true_index = [c for c in index if (yaw_diff[c] < cfgs.yaw_threshold) or (yaw_diff[c] > 360 - cfgs.yaw_threshold)]
有没有yaw > 180的情况？那样yaw_diff可能超越360-75，但还不是positive match，对吧？

2023-09-15 12:52 UTC, merged